/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.voting.app;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.Base64;
import java.security.Signature;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;

/**
 *
 * @author Inupa Vihan
 */
public class CountingCenter extends javax.swing.JFrame {

    static ServerSocket serverSocket;
    
    /**
     * Creates new form NewJFrame
     */
    
    public CountingCenter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        candidateAVoteCount = new javax.swing.JTextField();
        candidateBVoteCount = new javax.swing.JTextField();
        candidateCVoteCount = new javax.swing.JTextField();
        verification = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        candidateDVoteCount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sign = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        msg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Counting Center");
        setMinimumSize(new java.awt.Dimension(530, 410));
        setPreferredSize(new java.awt.Dimension(530, 410));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Signature Verification: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, -1));

        jLabel2.setText("Candidate B Vote Count");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 160, -1));

        jLabel3.setText("Candidate D Vote Count");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, -1));

        jLabel4.setText("Candidate C Vote Count");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 150, -1));

        candidateAVoteCount.setEditable(false);
        candidateAVoteCount.setText("0");
        candidateAVoteCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidateAVoteCountActionPerformed(evt);
            }
        });
        getContentPane().add(candidateAVoteCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 71, -1));

        candidateBVoteCount.setEditable(false);
        candidateBVoteCount.setText("0");
        getContentPane().add(candidateBVoteCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 71, -1));

        candidateCVoteCount.setEditable(false);
        candidateCVoteCount.setText("0");
        candidateCVoteCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidateCVoteCountActionPerformed(evt);
            }
        });
        getContentPane().add(candidateCVoteCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 71, -1));

        verification.setText("None");
        verification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificationActionPerformed(evt);
            }
        });
        getContentPane().add(verification, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 330, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setFocusable(false);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 160, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Counting Panel");
        jLabel9.setFocusable(false);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 179, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Security Observation Panel");
        jLabel10.setFocusable(false);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setFocusable(false);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, -1));

        jLabel5.setText("Candidate A Vote Count");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, -1));

        candidateDVoteCount.setEditable(false);
        candidateDVoteCount.setText("0");
        candidateDVoteCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidateDVoteCountActionPerformed(evt);
            }
        });
        getContentPane().add(candidateDVoteCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 71, -1));

        jLabel7.setText("Received Signature:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 120, -1));

        sign.setText("None");
        sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signActionPerformed(evt);
            }
        });
        getContentPane().add(sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 330, -1));

        jLabel12.setText("Receiving Msg:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, -1));

        msg.setText("None");
        msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgActionPerformed(evt);
            }
        });
        getContentPane().add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void candidateAVoteCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidateAVoteCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidateAVoteCountActionPerformed

    private void verificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verificationActionPerformed

    private void candidateCVoteCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidateCVoteCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidateCVoteCountActionPerformed

    private void candidateDVoteCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidateDVoteCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidateDVoteCountActionPerformed

    private void signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signActionPerformed

    private void msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static String msgIn = "";
    public static String msgOut = "";
    
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CountingCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CountingCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CountingCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CountingCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CountingCenter().setVisible(true);
            }
        });
        
        System.out.println("Counting Center Server");
        System.out.println("========================");

        try {
            serverSocket = new ServerSocket(6600);
            
            while (true) { 
                Socket socket = serverSocket.accept();
                System.out.println("Voting Center connected");

                // creating thread for each train connecting to the hub
                Thread clientThread = new Thread(new ClientHandler(socket));
                clientThread.start();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }  
    }
    
    private static class ClientHandler implements Runnable {
        private Socket socket;
        private DataInputStream din;
        private DataOutputStream dout;

        public ClientHandler(Socket socket) {
            this.socket = socket;
            try {
                din = new DataInputStream(socket.getInputStream());
                dout = new DataOutputStream(socket.getOutputStream());
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

        @Override
        public void run() {
            try {
                while (true) {
                    // String msgIn = din.readUTF();
                    String encryptedVote = din.readUTF();
                    System.out.println(encryptedVote);
                    String signature = din.readUTF();
                    System.out.println(signature);
                    
                    msg.setText(encryptedVote);
                    sign.setText(signature);
                    
                    int voteCountA = Integer.parseInt(candidateAVoteCount.getText());
                    int voteCountB = Integer.parseInt(candidateBVoteCount.getText());
                    int voteCountC = Integer.parseInt(candidateCVoteCount.getText());
                    int voteCountD = Integer.parseInt(candidateDVoteCount.getText());
                    
                    String decryptedVote = "None";
                    
                    try {
                        decryptedVote = verifyAndDecrypt(encryptedVote, signature);
                    } catch (Exception ex) {
                        Logger.getLogger(CountingCenter.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    switch(decryptedVote){
                        case "A":
                            voteCountA++;
                            candidateAVoteCount.setText(Integer.toString(voteCountA));
                            break;
                        case "B":
                            voteCountB++;
                            candidateBVoteCount.setText(Integer.toString(voteCountB));
                            break;
                        case "C":
                            voteCountC++;
                            candidateCVoteCount.setText(Integer.toString(voteCountC));
                            break;
                        case "D":
                            voteCountD++;
                            candidateDVoteCount.setText(Integer.toString(voteCountD));
                            break;
                        default:
                            System.out.println("Error");
                            break;
                    }
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            } finally {
                try {
                    din.close();
                    dout.close();
                    socket.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }
    
public static String verifyAndDecrypt(String encryptedVote, String signature) throws Exception{
    PrivateKey serverPrivateKey = KeyUtils.loadPrivateKey("keys/server_private.key");
    PublicKey clientPublicKey = KeyUtils.loadPublicKey("keys/client_public.key");
    
    byte[] encryptedVoteBytes = Base64.getDecoder().decode(encryptedVote);
    byte[] signatureBytes = Base64.getDecoder().decode(signature);

    Signature sig = Signature.getInstance("SHA256withRSA");
    sig.initVerify(clientPublicKey);
    sig.update(encryptedVoteBytes);
    boolean isVerified = sig.verify(signatureBytes);

    if (isVerified) {
        verification.setText("Successful");
        Cipher cipher = Cipher.getInstance("RSA");
        cipher.init(Cipher.DECRYPT_MODE, serverPrivateKey);
        byte[] decryptedBytes = cipher.doFinal(encryptedVoteBytes);

        String vote = new String(decryptedBytes);
        System.out.println("Received verified vote: " + vote);
        return vote;
    } else {
        System.out.println("Signature verification failed");
        verification.setText("Failed");
        return "Error";
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField candidateAVoteCount;
    private static javax.swing.JTextField candidateBVoteCount;
    private static javax.swing.JTextField candidateCVoteCount;
    private static javax.swing.JTextField candidateDVoteCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JTextField msg;
    private static javax.swing.JTextField sign;
    private static javax.swing.JTextField verification;
    // End of variables declaration//GEN-END:variables
}
