/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.voting.app;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Signature;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Inupa Vihan
 */

public class VotingCenter extends javax.swing.JFrame{
    
    static Socket socket;
    static DataInputStream din;
    static DataOutputStream dout;
    
    /**
     * Creates new form Hub
     */
    public VotingCenter() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vote = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Voting Center");
        setMinimumSize(new java.awt.Dimension(401, 311));
        setPreferredSize(new java.awt.Dimension(500, 330));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Candidate D");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, -1));

        sendButton.setText("Confirm & Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 120, 30));

        button1.setText("Vote");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Voting Panel");
        jLabel3.setFocusable(false);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 200, 30));

        button2.setText("Vote");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 100, -1));

        button3.setText("Vote");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 100, -1));

        button6.setText("Vote");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 100, -1));

        jLabel4.setText("Please insert your vote by clicking the vote button");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Your Vote: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 70, 30));

        jLabel6.setText("Candidate B");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 100, -1));

        jLabel7.setText("Candidate C");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, -1));

        jLabel8.setText("Candidate A");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, -1));

        vote.setEditable(false);
        vote.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        vote.setText("None");
        vote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voteActionPerformed(evt);
            }
        });
        getContentPane().add(vote, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        vote.setText("Candidate D");
    }//GEN-LAST:event_button1ActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String msgOut = "";
        
        String finalVote = vote.getText();
        
        if(finalVote.equalsIgnoreCase("None")){
            JOptionPane.showMessageDialog(
            this,
            "Please insert your vote",
            "Invalid Input",
            JOptionPane.ERROR_MESSAGE
            );
        }else{
            switch(vote.getText()){
                case "Candidate A":
                    msgOut = "A";
                    break;
                case "Candidate B":
                    msgOut = "B";
                    break;
                case "Candidate C":
                    msgOut = "C";
                    break;
                case "Candidate D":
                    msgOut = "D";
                    break;
                default:
                    msgOut = "None";
                    break;
            }
        
            try {
                // dout.writeUTF(msgOut);
                encryptAndSign(msgOut);
                vote.setText("None");
            } catch (Exception ex) {
                Logger.getLogger(VotingCenter.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        vote.setText("Candidate A");
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        vote.setText("Candidate B");
    }//GEN-LAST:event_button3ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        vote.setText("Candidate C");
    }//GEN-LAST:event_button6ActionPerformed

    private void voteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voteActionPerformed
        
    }//GEN-LAST:event_voteActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static String msgIn = "";
    public static String msgOut = "";
    
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotingCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotingCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotingCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotingCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>  
        //</editor-fold>
        //</editor-fold>  

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotingCenter().setVisible(true);
            }
        });
        
        System.out.println("Voting Center Client");
        System.out.println("========================");

        try {
            socket = new Socket(InetAddress.getLocalHost(), 6600);
            
            din = new DataInputStream(socket.getInputStream());
            dout = new DataOutputStream(socket.getOutputStream());
            
            while(true){
                msgIn = din.readUTF();
                System.out.println(msgIn);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
public static void encryptAndSign(String input) throws IOException, NoSuchAlgorithmException, NoSuchPaddingException, Exception{
    // Use relative paths that work from the bin directory
    PrivateKey clientPrivateKey = KeyUtils.loadPrivateKey("keys/client_private.key");
    PublicKey serverPublicKey = KeyUtils.loadPublicKey("keys/server_public.key");
            
    // Encrypt vote
    Cipher cipher = Cipher.getInstance("RSA");
    cipher.init(Cipher.ENCRYPT_MODE, serverPublicKey);
    byte[] encryptedVote = cipher.doFinal(input.getBytes());

    // Sign the encrypted vote
    Signature signature = Signature.getInstance("SHA256withRSA");
    signature.initSign(clientPrivateKey);
    signature.update(encryptedVote);
    byte[] signedEncryption = signature.sign();
                
    dout.writeUTF(Base64.getEncoder().encodeToString(encryptedVote));
    dout.writeUTF(Base64.getEncoder().encodeToString(signedEncryption));
    
    System.out.println("Encrypt and Signing Successful");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField vote;
    // End of variables declaration//GEN-END:variables
}
